# Generated by Django 3.0.6 on 2020-05-30 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 30, 2, 17, 19, 918546, tzinfo=utc), null=True),
        ),
    ]
